lexik_jwt_authentication:
    secret_key:       '%kernel.project_dir%/config/jwt/private.pem'
    public_key:       '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase:      '%env(JWT_PASSPHRASE)%'   # Vous allez définir cette phrase secrète dans l'étape suivante
    token_ttl:        3600   # Durée de validité du token en secondes (1 heure)
